Don't allow @node/types 13
Electron 7 and 8 rely on Node 12.  In node 13, NodeJS.EventEmitter becomes an interface, leading to the following failures:

```
node_modules/electron/electron.d.ts:1649:31 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

1649   class BrowserWindow extends NodeJS.EventEmitter {
                                   ~~~~~~

node_modules/electron/electron.d.ts:3007:31 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

3007   class ClientRequest extends NodeJS.EventEmitter {
                                   ~~~~~~

node_modules/electron/electron.d.ts:3435:25 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

3435   class Cookies extends NodeJS.EventEmitter {
                             ~~~~~~

node_modules/electron/electron.d.ts:3588:26 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

3588   class Debugger extends NodeJS.EventEmitter {
                              ~~~~~~

node_modules/electron/electron.d.ts:4113:30 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

4113   class DownloadItem extends NodeJS.EventEmitter {
                                  ~~~~~~

node_modules/electron/electron.d.ts:4482:33 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

4482   class IncomingMessage extends NodeJS.EventEmitter {
                                     ~~~~~~

node_modules/electron/electron.d.ts:5334:30 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

5334   class Notification extends NodeJS.EventEmitter {
                                  ~~~~~~

node_modules/electron/electron.d.ts:6179:25 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

6179   class Session extends NodeJS.EventEmitter {
                             ~~~~~~

node_modules/electron/electron.d.ts:7104:37 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

7104   class TouchBarColorPicker extends NodeJS.EventEmitter {
                                         ~~~~~~

node_modules/electron/electron.d.ts:7116:31 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

7116   class TouchBarGroup extends NodeJS.EventEmitter {
                                   ~~~~~~

node_modules/electron/electron.d.ts:7126:31 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

7126   class TouchBarLabel extends NodeJS.EventEmitter {
                                   ~~~~~~

node_modules/electron/electron.d.ts:7138:33 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

7138   class TouchBarPopover extends NodeJS.EventEmitter {
                                     ~~~~~~

node_modules/electron/electron.d.ts:7150:34 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

7150   class TouchBarScrubber extends NodeJS.EventEmitter {
                                      ~~~~~~

node_modules/electron/electron.d.ts:7166:42 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

7166   class TouchBarSegmentedControl extends NodeJS.EventEmitter {
                                              ~~~~~~

node_modules/electron/electron.d.ts:7179:32 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

7179   class TouchBarSlider extends NodeJS.EventEmitter {
                                    ~~~~~~

node_modules/electron/electron.d.ts:7193:32 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

7193   class TouchBarSpacer extends NodeJS.EventEmitter {
                                    ~~~~~~

node_modules/electron/electron.d.ts:7314:22 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

7314   class Tray extends NodeJS.EventEmitter {
                          ~~~~~~

node_modules/electron/electron.d.ts:7749:29 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

7749   class WebContents extends NodeJS.EventEmitter {
                                 ~~~~~~
Found 18 errors.
```

Since Electron doesn't need node 13 anyways, we should only allow minor and patch changes above @types/node 12