Add SkUserConfig.h with blank SkDebugf macro
This file was copied from:
./third_party/skia/include/config/SkUserConfig.h

But because of this linking error we needed to
define a macro for SkDebugf.

```
"SkDebugf(char const*, ...)", referenced from:
      SkBitmap::allocPixels(SkImageInfo const&, unsigned long) in
      libbrave_lib.a(brave_lib.native_desktop_media_list.o)
      ld: symbol(s) not found for architecture x86_64
```

There used to be a hack to copy this file here which was removed:
https://github.com/brave/libchromiumcontent/commit/8de9d9e2bcf455ba70e8005016150ab55690cb59