Patching download arch for arm
Electron no longer produces an 'arm' build, and now labels it 'armv7l'.  As NPM still uses 'arm', we need to patch the variable name here or the download fails with a 404 error like so:

 Error: GET https://github.com/electron/electron/releases/download/v3.1.3/electron-v3.1.3-linux-arm.zip returned 404