fix: linux test shutdown error "AttributeError: type object 'DBusTestCase' has no attribute 'stop_dbus'" (#51150)
stop_dbus() was removed on 2025-09-14 by
https://github.com/martinpitt/python-dbusmock/commit/99c4800e9eed27f3d26c28ba827fdb4b40c7b616

I think CI isn't seeing this yet because its image has an older version.

This patched script should work on old & new versions of python-dbusmock.

Co-authored-by: trop[bot] <37223003+trop[bot]@users.noreply.github.com>
Co-authored-by: Charles Kerr <charles@charleskerr.com>