Revert "move call to setEventEmitterPrototype earlier"
This reverts commit f5477bebb35eaffdf77fd9551ec9eb8d396a998d.

This broke with:

```
process.electronBinding('event_emitter').setEventEmitterPrototype(events_1.EventEmitter.prototype);
        ^

TypeError: process.electronBinding is not a function
```