build: gn: commit patches after they have been applied (#14147)
* chore: bump libcc

* build: gn: commit patches after they have been applied

It prevents a hooks run failure when `gclient sync` is called
for a second time. Error message:

```
error: ui/latency/ui_latency_export.h: already exists in working directory
latency_info.patch failed to apply
```