fix build-instructions-linux.md
:memo:
because if file is absent
IOError: [Errno 2] No such file or directory: 'your/path/electron/out/electron-api.json'